-- Kompletny schemat bazy danych dla aplikacji Skaner Tabliczek i Rejestr Operacji Saw-Trak
-- Uruchom poniższe polecenia w panelu Supabase -> SQL Editor

-- 1. Tabela 'wozki' (katalog maszyn i wózków widłowych):
CREATE TABLE IF NOT EXISTS wozki (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "Kod" text,
    "NRKATALOGOWY" text UNIQUE,
    "MODEL" text,
    "Marka" text,
    "Nazwa" text,
    "Opis" text,
    "TYP_WOZKA" text,
    "NR_FABRYCZNY" text,
    "ROK_PRODUKCJI" text,
    "UDZWIG" text,
    "SRODEK_CIEZKOSCI" text,
    "MASA_BEZ_AKUMULATORA" text,
    "MASA_AKUMULATORA_MIN" text,
    "MASA_AKUMULATORA_MAX" text,
    "NAPIECIE" text,
    "BATERIA" text,
    "TYP" text
);

-- 2. Tabela 'operacje' (rejestr wykonanych skanów i operacji serwisowych):
CREATE TABLE IF NOT EXISTS operacje (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    wozek_id bigint,
    nrkatalogowy text,
    model text,
    klient text,
    temat text,
    opis text,
    parametry jsonb,
    image_data text,
    parametry_ekranu jsonb,
    image_data_screen text
);

-- Dodanie kolumn do istniejącej tabeli 'operacje' w razie migracji ze starszych wersji:
ALTER TABLE IF EXISTS operacje ADD COLUMN IF NOT EXISTS opis text;
ALTER TABLE IF EXISTS operacje ADD COLUMN IF NOT EXISTS parametry_ekranu jsonb;
ALTER TABLE IF EXISTS operacje ADD COLUMN IF NOT EXISTS image_data_screen text;

-- 3. Nowa tabela 'zdjecia_operacji' (dodatkowe zdjęcia wózka, wideł, uszkodzeń, podzespołów powiązane z operacją):
CREATE TABLE IF NOT EXISTS zdjecia_operacji (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    id_operacji bigint REFERENCES operacje(id) ON DELETE CASCADE,
    image_dodatkowe text NOT NULL
);

-- Indeksy dla szybkiego działania:
CREATE INDEX IF NOT EXISTS idx_zdjecia_operacji_id_operacji ON zdjecia_operacji(id_operacji);
CREATE INDEX IF NOT EXISTS idx_operacje_wozek_id ON operacje(wozek_id);

-- 4. Wyłączenie RLS dla wszystkich tabel (najwygodniejsze dla aplikacji serwisowej):
ALTER TABLE IF EXISTS wozki DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS operacje DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS zdjecia_operacji DISABLE ROW LEVEL SECURITY;
