-- Skrypt SQL tworzący nową tabelę 'zdjecia_operacji' w Supabase
-- Uruchom poniższe polecenia w panelu Supabase -> SQL Editor

-- 1. Tworzenie nowej tabeli na dodatkowe zdjęcia powiązane z operacjami:
CREATE TABLE IF NOT EXISTS zdjecia_operacji (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_operacji bigint REFERENCES operacje(id) ON DELETE CASCADE,
    image_dodatkowe text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indeks dla szybkiego wyszukiwania zdjęć po id_operacji:
CREATE INDEX IF NOT EXISTS idx_zdjecia_operacji_id_operacji ON zdjecia_operacji(id_operacji);

-- 2. Wyłączenie RLS dla tabeli 'zdjecia_operacji' (zalecane dla bezproblemowego zapisu i odczytu):
ALTER TABLE IF EXISTS zdjecia_operacji DISABLE ROW LEVEL SECURITY;

-- 3. (Opcjonalnie) Jeśli używasz włączonego RLS, odkomentuj poniższe reguły bezpieczeństwa:
-- ALTER TABLE IF EXISTS zdjecia_operacji ENABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS "Zezwalaj wszystkim na odczyt zdjec_operacji" ON zdjecia_operacji;
-- CREATE POLICY "Zezwalaj wszystkim na odczyt zdjec_operacji" ON zdjecia_operacji FOR SELECT TO anon USING (true);
-- DROP POLICY IF EXISTS "Zezwalaj wszystkim na zapis zdjec_operacji" ON zdjecia_operacji FOR INSERT TO anon WITH CHECK (true);
-- DROP POLICY IF EXISTS "Zezwalaj wszystkim na usuwanie zdjec_operacji" ON zdjecia_operacji FOR DELETE TO anon USING (true);
