-- Skrypt SQL dodający pole 'opis' do tabeli 'operacje' w Supabase
-- Uruchom poniższe polecenia w Supabase -> SQL Editor

-- 1. Dodanie kolumny 'opis' do istniejącej tabeli 'operacje' (MIGRACJA):
ALTER TABLE IF EXISTS operacje ADD COLUMN IF NOT EXISTS opis text;

-- 2. Pełna definicja tabeli 'operacje' (dla nowej bazy):
CREATE TABLE IF NOT EXISTS operacje (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    wozek_id bigint,
    nrkatalogowy text,
    model text,
    klient text,
    temat text,
    opis text,
    parametry jsonb,
    image_data text,
    parametry_ekranu jsonb,
    image_data_screen text
);

-- 3. Wyłączenie RLS dla tabeli 'operacje' (zalecane dla prostej integracji):
ALTER TABLE IF EXISTS operacje DISABLE ROW LEVEL SECURITY;
